### ISSUE TITLE
Provide a clear message that data is still being loaded to course members when the cron has not populated the course data

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1046]
## Describe your problem or feature you'd like added
When an instructor adds MyLA as an LTI to a course, the cron has to run before the enrollment on that course is added to MyLA.  If students,TAs, or other assistants & teachers access the course before the cron runs, they get an error message.  It would be better for them to get a message that displays the same icon the instructor who added MyLA sees that indicates the data is still being loaded.

## Describe the solution you'd like
1. Instructor adds MyLA to a course
2. Before cron runs, a student, TA, or other teacher in the course accesses MyLA for that course
3. MyLA LTI displays the icon from #964 that shows the data is being processed.

**Comment by pushyamig** [comment]
When instructor add Myla and launches Tool for first time, we make a row entry in the `user` table. so that's why he don't see permission denied error and from the call course info `/info` call gives an attribute `['course_data_loaded'] 0 or 1` based on `term_id` in the `course` table

In the mean time when if other users launch mYLA, cron is not run they see 403

[Django-rule](https://github.com/dfunckt/django-rules) library is handling this and I don't think we are exclusively setting HTTP code. 
We have to identify the case cron not run (`term_id` is not added in `course` table) when rule checking is made and set a different HTTP code. We need to dig more if Django rule library allow us to add exclusive statue code so that based on that we can show same course data not loaded icon to all. 

IF this case solved then we don't need add instructor entry into user table at all and cron add all user when run

**Comment by chrisrrowland** [comment]
|   |  | Mode | Loaded | Visibility | admin | instructor | student | non-student |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  GERMAN 102 WN 2020 | https://umich.test.instructure.com/courses/335188/external_tools/28133 | LTI | yes | Course | yes | yes | yes | access denied |
|  CHEM 462 100 FA 2015 | https://umich.test.instructure.com/courses/5892/external_tools/28133 | LTI | no | Course | CDBP | CDBP | CDBP | access denied |
|  CHEM 453 100 FA 2020 | https://umich.test.instructure.com/courses/384425/external_tools/28133 | LTI | no | Institution | CDBP | CDBP | CDBP | CDBP |
|  GERMAN 102 WN 2020 | http://localhost:5001/courses/335188/ | Standalone | yes | n/a | yes | yes | yes | no access or course being loaded |
|  CHEM 453 100 FA 2020 | http://localhost:5001/courses/384425 | Standalone | no | n/a | CDBP | CDBP | N/A | CDBP |

**Comment by chrisrrowland** [comment]
I need to remember not to put comments in that close issues automatically

**Comment by chrisrrowland** [comment]
Thought I caused the issue to be closed erroneously with a closes issue comment, but I think it's supposed to be closed to go to QA

**Comment by jennlove-um** [comment]
Tested adding a course and viewing as admin, instructor, ta, student, and observer.  Image displayed correctly for all user types when data had not yet been loaded.  Data displays correctly for enrolled students after cron run.
