### ISSUE TITLE
AssignmentV2 is not scrolling to current week

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#1147]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 
When a user launches new assignment redesign, the table should auto scroll to a current week ( that is being calculated and week is slight orangish color), the Scrolling feature is broken right now.
![Screen Shot 2020-12-09 at 9 09 04 AM](https://user-images.githubusercontent.com/8579775/101640247-48c0bf80-39fe-11eb-8cef-d369a9c78770.png)

The feature mostly useful when loading the view.

**Comment by pushyamig** [comment]
Test Plan: Choose a course that has a start date align with course Home work dates assignments that in turn align with current date of the date you are testing.
I tested with this fall course (380342) and is currently aligned with current date when made the fix

**Comment by pushyamig** [comment]
Test Plan: different scenarios to test
1. User never sets an course Goal, consider this case as user first visits the site
2. User Set a course goal and try launch the view after the goal set
3. User clears course Goal and try launches the view after that

In all 3 scenarios the table should scroll to the orangish color week.

**Comment by jennlove-um** [comment]
@pushyamig I'm seeing odd behavior in test, but I'm not sure if this is because this issue is not done yet.  When I try to enter a score for an assignment prior to the current week, the view keeps resetting the list to focus on the current week.  So I have to keep scrolling back up after I try to select the goal I want to set.

![AP_ViewRecentersToCurrentWeek](https://user-images.githubusercontent.com/39634416/102411304-b8671980-3fbf-11eb-9d59-70a8571e1d68.gif)

**Comment by chrisrrowland** [comment]
> @pushyamig I'm seeing odd behavior in test, but I'm not sure if this is because this issue is not done yet. When I try to enter a score for an assignment prior to the current week, the view keeps resetting the list to focus on the current week. So I have to keep scrolling back up after I try to select the goal I want to set.
> 

This definitely needs some tweaks.  There is code that fires when the inputs gain/lose focus.  Those focus/blur handlers add a significant amount of lag to the view as well.  From what I can tell in researching it is indirectly used to prevent goals that were not just set from getting rounded, otherwise it would be simple to eliminate.  Spoke with @justin0022 about it and he is going to take a look as well.  Hoping we can just get rid of those handlers.

Aside from that we can additionally add a simple boolean that prevents the scroll from happening more than once.  

@pushyamig noticed this scrolling behaviour when testing assignment goal input debouncing and i have tested the aforementioned solutions and it seems like they should fix the issue.

**Comment by justin0022** [comment]
I'll do a deeper dive on this tomorrow

**Comment by jennlove-um** [comment]
Testing passes: The view correctly defaults to the current week and keeps the correct focus when students are manipulating assignment grades.
