### ISSUE TITLE
cron job did not bring in ungraded submissions

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1193]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 

As requested in [issue_976](https://github.com/tl-its-umich-edu/my-learning-analytics/issues/976), we want to show both submitted assignments as well as graded assignments.

### Describe the bug (Tell us what happens instead of the expected behavior) :

The cron job currently only bring in graded submissions. 

We want to show submissions once submitted.

### Steps to Reproduce :
1. find a site with ungraded but submitted assignments 
2. add the MyLA tool to the site
3. after the cron run, log in with student with not-graded assignment submission, the student won't see that assignment as already "submitted".

**Comment by pushyamig** [comment]
@jennlove-um Can you give few test courses to test around various cases of assignment submission/grading?

**Comment by jennlove-um** [comment]
Testing notes: For this release, we are not pulling in date for courses have a graded date but no posted date.  This prevents students from seeing grades for any assignments that have been graded but the grades have not been released to the students.  

Testing scenarios: 
1 - Submitted, graded, and posted --> Passes: assignments show up as graded in MyLA
2 - Submitted, graded, and NOT posted --> Passes: assignments show up as unsubmitted and ungraded
3 - Submitted, not graded, and not posted --> Passes: assignments show up as pending grade
4 - Not submitted, not graded, not posted --> Passes: assignments show up as unsubmitted and ungraded

Future releases will address a way to get the data for scenario 2 above so that these assignments can show up as pending grade without any risk of showing students assignment grades that have not yet been posted.
