### ISSUE TITLE
Make git check optional

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1206]
### Expected behavior (A description of what you expected to happen) : 

MyLA deploy should work with direct source download and without git integration.

### Describe the bug (Tell us what happens instead of the expected behavior) :

According to @andrew-gardener: "...I ran into the issue previously when deploying myla. It happened because I built the docker image in a CI using a source release download when making the image (so the image did not contain a .git and the git commands would throw an non blocking error on startup since the folder wasn't a git repo)."

**Comment by ssciolla** [comment]
I tested by

**Comment by ssciolla** [comment]
I tested by adding a build step to `Dockerfile`: `RUN rm -R /code/.git` and commenting out the volume mapping `.:/code:delegated` under `web` in `docker-compose.yml`. Nothing breaks with these changes, but the resulting Git info block for admins looks kinda silly:

<img width="200" alt="Screen Shot 2021-02-09 at 1 21 35 PM" src="https://user-images.githubusercontent.com/35741256/107409187-e48faa00-6ad9-11eb-9e9e-3152b550e2d2.png">

@zqian, I will propose some changes to the `util` function that does this work (and maybe the template), so that this just gets hidden instead when there's no `.git`. As a fallback, I think it would be okay to release as is, since nothing breaks and it's only an admin feature.

**Comment by andrew-gardener** [comment]
of note is that we're still using it (without a `.git` directory) by passing in the environment variables directly. So maybe make it so that its hidden only when there are no environment variables for commit and/or branch

**Comment by ssciolla** [comment]
Good to know, @andrew-gardener, please see PR #1234

**Comment by ssciolla** [comment]
I'm going to mark this as done. The improvements I proposed are now linked to issue #1236.
