### ISSUE TITLE
update job must pull null-grade submissions

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1208]
(cron job needs to pull in submissions with null grade, if the submission has been graded but grades are not released)

### Expected behavior (A description of what you expected to happen) : 

Instructors may grade on assignment submissions, but wait till later date to release those grades.

### Describe the bug (Tell us what happens instead of the expected behavior) :

Currently, MyLA cron job does not pull in those "graded but grades are not released yet" submissions

### Steps to Reproduce :
1. Before submitting to an assignment, student will see this assignment marked as "unsubmitted" in Assignment Planning view
2. Student submit an assignment
3. After MyLA cron job, student can view the assignment as "submitted but not graded"
4. Instructor graded the submission without releasing it
5. After another MyLA cron job, student now see the assignment as "unsubmitted" again.

**Comment by jonespm** [comment]
What's the difference between this one and #1193?

I feel like this SQL might be getting too many special cases in it. Isn't it possible to check something else like workflow_state or just trust if the posted_score is null then there's no score?

**Comment by zqian** [comment]
@jonespm I have rewritten the logic in attached PR, to import grades iff posted_at value is not null. Hopefully simplifies the logic in the query.

**Comment by jennlove-um** [comment]
@zqian The data is getting pulled as expected.  However, it's working in unexpected ways in the Assignment Planning view: 

For assignments that have been submitted and graded, but grades aren't released: 
- Score displays as null/points (e.g., null/100) instead of 0/points
![image](https://user-images.githubusercontent.com/39634416/108114986-8299ec00-7067-11eb-9451-a994a8f2f1d5.png)


- Mouseover text shows the "Your Grade" and "Class Average" as 0.  It should hide both of those fields the same way that ungraded assignments do.
![image](https://user-images.githubusercontent.com/39634416/108116065-0d2f1b00-7069-11eb-93e8-d386018c9836.png)

![image](https://user-images.githubusercontent.com/39634416/108116169-289a2600-7069-11eb-98c4-3938c0f76a91.png)

**Comment by jennlove-um** [comment]
This issue needs to also take into account changes that need to be made in the UI to use the data as expected for assignments that have been graded but the grades are not posted: 

1. Do not factor these grades into Current grade in the top bar (treat them like submitted but ungraded assignments)
2. Display them as pending & filter as pending (like submitted but ungraded assignments)
3. Display either the goal (if one is set) or 0 for the assignment score (not "null")
4. The mouseover should display the same data as submitted but ungraded assignments (don't include the Your grade or Class average fields)

**Comment by zqian** [comment]
Reopen the issue since the change caused "null" string show up in the UI, and broke the "filter by status" dropdown filter.
![unreleased_grade](https://user-images.githubusercontent.com/359944/108121203-6b133100-7070-11eb-8363-2d396d1675b4.png)
