### ISSUE TITLE
Value LTIlaunchID is always set as undefined. Should remove this from frontend or fix.

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1240]
### Expected behavior (A description of what you expected to happen) : 
Frontend globals.js is setting
`  LTIlaunchID: mylaGlobals.lti_launch_id,`

However this value is not provided by the backend currently. This was noticed as part of the newer survey feature in #1216.

### Describe the bug (Tell us what happens instead of the expected behavior) :
So it looks like it was removed from the front and backend here when there was a refactor to use get_myla_globals in #1009. But it was added back into the frontend here: (I'm guessing because of a merge conflict?) in #1008. I'm not sure how to get this data easily into this variable if it's desired, might be a little work. 

We also need to check if this value is even useful to the survey in #1216, if it's not we should just clean up LTIlaunchID from the globals.js rather than trying to fix this. 

### Steps to Reproduce :
1. Launch MyLA with LTI
2. Inspect the HTML, notice that LTIlaunchID is not defined in myla_globals. 
3. You can check this by running on the console
`JSON.parse(document.getElementById("myla_globals").textContent)["LTIlaunchID"]`
That value should return something, it returns unknown.
This will return the username `JSON.parse(document.getElementById("myla_globals").textContent)["username"]`

**Comment by pushyamig** [comment]
The LTI Launch ID is something that is tied up with the PYLTI1.3 package. It creates the launch ID for keeping track of the LTI launch information and if in future wanted to use LTI advantages services like Assignment and Grading service then PyLTI1.3 based on the launch ID it can look up the user details and make the necessary calls to Canvas. But MyLA don't use LTI advantage services.

The launch ID should be stored somewhere after LTI launch since that is  key to making further conversation with Canvas. Currently Myla doesn't support since after the LTI launch myla is server redirect to `/course/1223` so that leads to storing the Launch ID in the session context. So by default Django stored the session in DB we can store the launch id there. But the catch there is once we use the Django Become user feature it will wipe out the session info since becoming user from django is not an LTI launch.

**Comment by pushyamig** [comment]
You can remove the frontend global variables. I don't know how useful this id is for survey since it  can give user identification info that is stored in `django_myla_cache` in the `value` column

**Comment by jennlove-um** [comment]
Remove this value from the globals per conversation in MyLA-dev today.

**Comment by jennlove-um** [comment]
I'm closing this issue.  The value has been removed from globals.
