### ISSUE TITLE
First week of events missing from Resources Accessed view

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#1289]
### Expected behavior (A description of what you expected to happen) : 
The Resources Accessed view should show all files that have been accessed during the specified time period.  

### Describe the bug (Tell us what happens instead of the expected behavior) :
Not all files are being included in the view.  In an example test course, students have accessed 5 files and 2 videos.  That data is present in the resources_accessed table in the database.  However, the view shows only 3 files and 1 video.  

Sample test course ID: 511607

**Comment by jonespm** [comment]
So the problem here is that we have a "off by one" (week in this case) error in the code. 

So it doesn't actually pick up any actions in the first week of class. The "quick fix" for this is to move the start date back a week for this course in the admin UI. 

We'll get a code for for this soon. I'm reviewing the SQL here as it seems like it's inefficient and returning way too many rows.

**Comment by jonespm** [comment]
Okay, the view looks good, putting in a PR for the fix.

**Comment by jennlove-um** [comment]
This passes in testing.  I'm seeing resources display for the weeks as expected.
