### ISSUE TITLE
Github href at bottom of page should open in new tab

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1347]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 
When you click on the GitHub SHA link on the bottom of the page, since it's in an iframe it opens to a blank page. It should open to a page that works in Github. I think we'll have to have it open in a new tab.

### Steps to Reproduce :
1.  Click the Github SHA at the bottom of any page
2. Should be able to see the Github info
3.

### Screenshots/Video (If possible, add media to help explain your problem) :
![image](https://user-images.githubusercontent.com/27447/140784843-976045c9-9c8e-4d5d-bcbf-9d50824c6057.png)

**Comment by saputran** [comment]
Hi @jonespm! I'm a student in EECS 481 interested in working on this issue.

**Comment by saputran** [comment]
I've downloaded the files and Docker/Git, but when I try to run the localhost, I get this error. Do you know why this may be?
![image](https://user-images.githubusercontent.com/44738429/158078849-70a227e5-0047-4254-8195-4aaceeb38489.png)

**Comment by zqian** [comment]
Hi, Natasha:

Thanks for your interest in working with My Learning Analytics(MyLA) code
base.

The MyLA README page
<https://github.com/tl-its-umich-edu/my-learning-analytics> explains that "MyLA
Supports LTI 1.3, using pylti1.3 <https://github.com/dmitry-viskov/pylti1.3>
. Instructions for LTI 1.3 configuration are in the MyLA wiki
<https://github.com/tl-its-umich-edu/my-learning-analytics/wiki/Dev%7CDeploy:-Configuration-for-LTI-1.3>
"

Otherwise, you can set the following environment variable to be fase for
local development:

"STUDENT_DASHBOARD_LTI": false

Please let us know if you have further questions.

Best,
- Zhen

------------------------------------------------------------------------------------------------------

Join the future of quizzing in Canvas!
<https://its.umich.edu/academics-research/teaching-learning/canvas/new-quizzes>

Zhen Qian [image: A button for name playback in email signature]
<https://www.name-coach.com/zhen-qian-ba96957f-e2c1-4a55-aee6-32c8ae3daf2b> |
zqian | Teaching & Learning Application Developer Manager

**Comment by saputran** [comment]
Hi Zhen,

Thank you for your help - I'll use this!

Have a great night,
~ Natasha

**Comment by saputran** [comment]
Hi Zhen,

I wanted to ask if I could create test courses/etc. using a random course ID just for testing (and delete it afterwards)?

**Comment by jonespm** [comment]
Hi, sorry, I was off most of last week.

Locally you can create anything you like for testing. Everything is just saved on your local machine and you can remove the Docker Image or database when you're done.

**Comment by zqian** [comment]
Right. Natasha, if you follow the README file, in the 10th step of "installation and setup" section, it says "Download the latest SQL file from this link: https://drive.google.com/drive/u/0/folders/1Pj7roNjRPGyumKKal8-h5E6ukUiXTDI9."

You will get sample data including courses, assignments, files, etc. to get you started for local development

**Comment by jennlove-um** [comment]
Testing passes in MyLA beta - Github link opens in new window.
