### ISSUE TITLE
Check if Deployment ID claim is missing and return an error even if validation if disabled

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1396]
We failed the certification because we allowed missing deployment ids. We could probably turn this on and validate it but if it's missing completely this should have an error and fail. 

It looks like from the spec that this is required to be present but it doesn't necessarily need to be validated. https://www.imsglobal.org/spec/lti/v1p3#lti-deployment-id-claim

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/3d0a1ccb71e6461775ac620b642e8ecc5047fd03/dashboard/lti_new.py#L41

**Comment by pushyamig** [comment]
I will QA this

**Comment by pushyamig** [comment]
https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1401#issuecomment-1248119686

**Comment by pushyamig** [comment]
Test passes. 

I couldn't set a null to deployment id since canvas always sending it and we cannot control that from Canvas instance. I think it will be a overkill to use the 1Edtech LTI test suit for resolving this issue 

So What I did is I throw an error when `_get_deployment_id()` is called and that's a way I am mimicking it.

**Comment by jonespm** [comment]
That sounds good! I plan to run the 1EdTech test probably next week, hopefully on Monday so we'll see if it passes that or not. But looks it should be fine.
