### ISSUE TITLE
Upgrade to latest Apollo 3.8 might have adverse effects on Assignment planning

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#1525]
Assignment Planning V2 is crashing from the latest code. This is the below error. The problem is caused since the way the object items are added once created. This part of the code has not changed with recent [commits](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/assets/src/util/assignment.js#L208) 

`TypeError: Cannot add property week, object is not extensible`

https://umich.beta.instructure.com/courses/562259/external_tools/54703

**Comment by jonespm** [comment]
This is _likely_ caused by changes in the apolloclient because it got upgraded without us realizing. #1527 holds back the version but we first saw this in 3.8.1. I believe it's related to some of the work as mentioned on <a href="https://github.com/apollographql/apollo-client/issues/5987">this issue</a>

**Comment by jennlove-um** [comment]
Testing passes in beta - Assignment Planning view is functioning as expected for students and instructors.
