### ISSUE TITLE
Upgrade to Frontend Dependencies

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#1529]
It's time we update the Myla Major FE libraries like React 8 and Material UI 5 we are one version behind. We are going to see a possible issue when Upgrading to ApolloClient as listed here https://github.com/tl-its-umich-edu/my-learning-analytics/issues/1525

----------
Test Plan
https://docs.google.com/spreadsheets/d/18c_VDE7wdme8c36Zo5-pjad77Kit8hFz4ylbmFXmLP8/edit#gid=0

**Comment by jaydonkrooss** [comment]
So this is my PR against @pushyamig's branch to address the styling regressions that we saw with the Material UI upgrade: https://github.com/pushyamig/my-learning-analytics/pull/11

Also just noting some other styling differences that Jennifer uncovered that we do **not** need to revert: 
- Assignment Planning: the "clear" and "clear filters" buttons are set to blue when enabled
- Assignment Planning: the "Set a goal" input field is now a outlined text field rather than the standard underlined input

**Comment by pushyamig** [comment]
Adding the test plan https://docs.google.com/spreadsheets/d/18c_VDE7wdme8c36Zo5-pjad77Kit8hFz4ylbmFXmLP8/edit#gid=0

**Comment by jennlove-um** [comment]
Testing passes in beta
