### ISSUE TITLE
instructors view to become student in the course

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#309]
There is a curiosity among the group to have an instructor view to become user from a course that they are teaching instead of giving them admin access

**Comment by jonespm** [comment]
This would require
- Verifying that a user is an instructor in the course
- (Probably) Providing the instructor a nice UI to select both a course and student to become. (Rather than making them enter their uniqname)

Is this something that students should have control to opt-out of? This *seems* more like an advisor style role than instructor, so not sure where those lines are?

**Comment by jennlove-um** [comment]
I'm concerned about student privacy with this one.  If we allow instructors to view as an individual student, then they can see which files the student has or hasn't viewed.  That information feels important for instructors to have at the aggregate level, but not at the individual student level.

**Comment by jonespm** [comment]
This is also not something that Canvas allows an instructor to do. They can do a generic "student view" but not view a specific student. I'm not sure how a generic student view would differ much from a generic instructor view of a course. I have the same concerns as Jennifer, it seems like there's good reason they can't act as someone individually.

**Comment by jennlove-um** [comment]
I'm going to close this issue as something we're not going to do for now.  We know we want the instructor to be able to view the dashboard visualizations, but we don't want them to be able to "become user" to be a student in their courses.
