### ISSUE TITLE
Restrict the MyLA tool access to the people belonging to the  course only

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#314]
Currently, the tool is accessible to anyone who has uniqname, once anybody figured out the course id can access the course analytics views. 
This could be controlled by restricting access only to the people in the course. The DB tables only have student enrollment data. We need to bring in the Teacher enrollment data to restrict instructors viewing only his course content. A question to answer is which enrollment type need access to tool? like TA/Observer.

**Comment by pushyamig** [comment]
Assigning to @jennlove-um for review with the team

**Comment by andrew-gardener** [comment]
There are a few issues around access control (#309, #132, and this) and was wondering what strategy was planned for implementing it? Mainly I'm wondering if access control would be populated by the cron job, LTI, and/or user specific queries to the data warehouse?

I can help out with this if it isn't already underway (it will be import for us to implement if we want to run the pilot on multiple courses).

**Comment by jonespm** [comment]
Yeah currently our access is controlled via Shibboleth. Anyone that knows the URL can login but it's typically launched via a link in Canvas. (We're using a javascript that adds in the link at the moment rather than LTI launched) 

If you happen to know the course ID general information about the course will shown but unless you actually are on with a user with data there's nothing much available besides the grade distribution and assignments available (without any scoring data). Administrators added can su to other users to see their data. (We've had requests for instructors or non-admins to do that but currently that feature is on hold)

I feel like for this request we'd minimally want to pull more data (probably from enrollment_dim) for the courses we support and only allow access to the courses if the user is enrolled. That's basically what this was going after. 

Everything is currently populated by the cron job but eventually we'd like to use the UDP for this data like others. If you were launching via LTI I guess you could trust that.

So yeah, I guess for us
- (Us Now) Cron populated from Canvas enrollment data
- (Us Future) UDP or via LTI launch (Probably would need to support both)

**Comment by jonespm** [comment]
I think this is something we really should have for spring. Even though the generic views don't give much information anyone that could login could possibly get into these views at the moment.

**Comment by andrew-gardener** [comment]
I've began working a bit on this. I wanted to check if this approach will work with you guys

- Add a `CANVAS_PRIMARY_AUTH_PROVIDER_ID` env variable that stores the id of the primary authentication account used for users 
- add `enrollment_type` column to `user` table
- change https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/dashboard/cron.py#L128 to
```
with enrollment as (
  select DISTINCT e.user_id, e.type, c.current_score, c.final_score
  from enrollment_dim e
  left join course_score_fact c ON c.enrollment_id = e.id
  where e.course_id = '{UDW_course_id}'
  and e.workflow_state = 'active'
  and e.type in ('StudentEnrollment', 'TaEnrollment', 'TeacherEnrollment')
)
select u.name as name,
           p.sis_user_id as sis_id,
           p.unique_name as sis_name,
           u.global_canvas_id as id,
           e.current_score as current_grade,
           e.final_score as final_grade,
           e.type as enrollment_type
from user_dim u
join pseudonym_dim p ON p.user_id = u.id
join enrollment e ON u.id = e.user_id
where p.workflow_state = 'active'
and p.authentication_provider_id = '{settings.CANVAS_PRIMARY_AUTH_PROVIDER_ID}'
```

This should fetch one row with optional grades for each instructor, ta, and student (handling multiple enrollments for multi section courses). Also `CANVAS_PRIMARY_AUTH_PROVIDER_ID` is useful since it handles situations where users have multiple pseudonyms (also pseudonym_dim.sis_user_id is empty for some tas/instructors so can't filter by that being present or not).

**Comment by jennlove-um** [comment]
Testing passes: 

1. enrollment_type has been added to the user table

2. users (teachers & students) can access pages for courses that they are enrolled in

3. users (teachers & students) cannot access pages for courses that they are not enrolle din
