### ISSUE TITLE
Cron job should send notification when course fails but continue to load other course data

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#383]
When there is an invalid course ID or the cron job cannot get the data for some reason, it should do the following: 

1. Log the error and send a notification to production support
2. Continue to load data for valid courses

**Comment by jonespm** [comment]
This was partially done in #292 .

This just sounds like a suggestion for handling this better. 

1. This is already logged but we don't have a good notification process yet for cron jobs
2. Should be easy to deal with from the code that was already implemented.

**Comment by ssciolla** [comment]
Because `cron.py` is not set up to update courses individually or incrementally, I don't think it is necessary to implement this feature yet. Right now the cron job will log an error and stop if an invalid ID is found, meaning that no further queries will be made.

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/4163cf2386d975b0b765d9564620f1521a9641d8/dashboard/cron.py#L486-L491

If we made it so it would continue and update the valid courses, we'd still have to run the cron again to gather data for the invalid courses (which would mean we'd update the courses that already ran successfully again). Based on how the cron is currently written, I think it makes sense to only execute all the queries if all the IDs are valid. In addition, we're unsure what form the cron will take in the future, meaning it may not make sense to rework this just yet.

I will close the issue for now, though we keep this idea in mind in case circumstances change to where it would make sense.
