### ISSUE TITLE
Schema used for Caliper events (files accessed)?

### ISSUE THREAD

**Issue by andrew-gardener** [tl-its-umich-edu/my-learning-analytics#413]
I was wondering if you were willing to provide the schema for your caliper events table https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/dashboard/cron.py#L234 (wanted to see about aligning with it to help with files accessed view and other future dashboards)

**Comment by jonespm** [comment]
This is the schema
https://rawgit.com/unizin/udp-docs/master/udp/old/lrs-event-record.html

Most of the columns are parsed out of the event and stored in columns. The "event" column is the JSON payload but as this mentions if it's eligible for "enrichment" Unizin it adds additional attributes to the JSON payload.

This extra data is

```
"extensions": {
      "com.unizin.canvas":{  
         "ucdm_course_offering_id":"12345678",
         "ucdm_actor_id":"12345678"
      }
}
```

This is just to releate this event between the UCDM (which is their SIS data) and the caliper event. We are not using this in MyLA only the standard caliper. 

We could probably change it to JSON_EXTRACT_SCALAR from everything rather than use the custom columns. The query could be probably changed to work with something other than BigQuery then if it was just running against the value.

**Comment by andrew-gardener** [comment]
Thanks, this helps a lot!

**Comment by jonespm** [comment]
Cool, here's a super quick sanitized record. All of the columns 

actor_id and course_offering_id are the values in the caliper event without the "canvas data" addition. (So just like 1234 instead of the 1000000000000000001234). Type and Action are pulled out of the event to their own columns for (possibly) a slight performance improvement. 

This is still development so may change. They say when we move to UDP we won't be querying these directly either so we'll have to rewrite this. I believe this cut over is supposed to happen sometime in the next few months but we don't know exactly what it will look like. 

```
id,type,action,event_time,ed_app,course_offering_id,actor_id,event,store_time,ucdm_course_offering_id,ucdm_actor_id

00000000-0000-0000-0000-000000000000,GradeEvent,Graded,2018-01-01 00:00:00 UTC,http://test.instructure.com/,10000000000000000,100000000000000000,"<CALIPER JSON EVENT>",0001-01-01 00:00:00 UTC,00000000,000000
```
