### ISSUE TITLE
frontend tests

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#426]
Front-end using the jest framework

**Comment by pushyamig** [comment]
I am just assigned to @justin0022 demonstrate tests with but later we will all add tests who event worked on the respective views.

**Comment by pushyamig** [comment]
@justin0022 I am assuming these are not unit test

**Comment by justin0022** [comment]
I think it'll be a mix of unit and integration tests. I'll add some tests for the grade distribution page and we can discuss further once I've done so.

**Comment by jonespm** [comment]
I think unittests will be separate and this is something I'm planning on working on. Most of the packages I've written have had unittests but without suitable mock data there didn't seem to be as much in MyLA to test. I think we're really close to having that and can do it.

Also I've heard a lot of preference to pytest over unittest. I've also used unittest in the past and am open to switching over especially since it looks like[ pytest can run unittest](https://docs.pytest.org/en/latest/unittest.html) and it looks like the [only real advantage](https://github.com/renzon/pytest-vs-unittest) is unittest is built in? 

In any case I think these are going to be separate.

**Comment by justin0022** [comment]
I was just referring to unit tests on the front end - not as familiar with testing Python code. 

For example, I'm going to add unit tests for the math utils file here: https://github.com/tl-its-umich-edu/my-learning-analytics/blob/react/assets/src/util/math.js.

**Comment by Adonais0** [comment]
To my understanding, the tests can be split into three parts: 

- Jest snapshot test for D3
- Unit test for utility functions
- Enzyme test for React components and hooks (not sure if we want this?)

Are these all the tests we want to do with the front-end?

**Comment by justin0022** [comment]
We might add functional and integration tests in the future, but for now I think the snapshot/unit/component tests should be a good start.

**Comment by justin0022** [comment]
[@soohyunkim](https://github.com/soohyunkim), a student staff on our team, is currently working on creating the rest of the snapshot tests. She'll send a PR soon.

**Comment by justin0022** [comment]
I'm working on writing enzyme tests for the container components - starting with `GradeDistribution.js`.

**Comment by pushyamig** [comment]
@justin0022 this doesn't need to be a done for getting the react merged to master. We can work on this later. Just list the things needs to be done so we can break into the separte task later

**Comment by jonespm** [comment]
This one is also related to #879

**Comment by jennlove-um** [comment]
I'm closing this issue.  No work has been done on it since 2019 and there are not immediate plans or resources to continue.
