### ISSUE TITLE
file_access table is created wrong using Django Migration

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#494]
It looks like with recent [commit](https://github.com/tl-its-umich-edu/my-learning-analytics/commit/e8288a8f094202cf5bf1f4da7be817f099d369ad) the file access table column name look like this `[file_id_id, user_id_id]` instead of `[file_id, user_id]`. 
 The simple fix seems to be adding this attribute to the `FileAccess` model for `file_access` `db_column=file_id` and `db_column=user_id`

This is leading to cron data is not able to load properly and cron is not event erroring saying the table column name mismatch.

Probably the [existing](https://github.com/tl-its-umich-edu/my-learning-analytics/blob/master/dashboard/migrations/0001_initial.py) migration files need to be dropped and new one should be created.

Unless this issue is fixed the migration changes should not be pulled into the react branch

**Comment by jonespm** [comment]
I ran liquibase on this migrated database compared to the existing. Besides these file_access issues there were a few others

CHAR(255) were changed to VARCHAR.
FLOAT(12) was changed to DOUBLE(22)
Some TIMESTAMP's was changed to DATETIME

A few nullable fields were changed from false to true. I'll create a new issue as we need to change this on the initial migration and change them later or change them on our production. This issue is the only column name change and is the bigger immediate issue.
