### ISSUE TITLE
Convert myla_globals from JavaScript object to JSON and use JSON.parse

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#556]
According to [this article](https://v8.dev/blog/cost-of-javascript-2019#json), JSON is much faster to parse than JavaScript objects.

**Comment by jonespm** [comment]
> "A good rule of thumb is to apply this technique for objects of 10 kB or larger — but as always with performance advice, measure the actual impact before making any changes."

myla_globals is under 1KB right now.

I don't think for our app it *really* matters that much since this variable is only put into the DOM once and then just reused by react "as-is" until the user actually refreshes the page, right?

Maybe if we had the myla_globals on come from an api? This is interesting though and not sure how this works?

It looks like eval has some caching implemented that can make it twice as fast as JSON.parse for "known data" but much slower for unknown data. 
https://tomdale.net/2017/07/adventures-in-microbenchmarking/

**Comment by justin0022** [comment]
Good point, the performance difference is probably negligible.
