### ISSUE TITLE
Assignment Planning - Data for graded and ungraded assignments is incorrect

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#578]
In the Assignments Planning view, the assignment grade data is showing up incorrectly.  The display does not match what is in the database.  Sometimes graded assignments are showing up as ungraded.  Sometimes graded assignments are showing up with the wrong grade in the tooltip.

**Comment by pushyamig** [comment]
Well, this bug is encountering when Assignment with weights associated in a group that is hidden in a group. The problem is encountered due to all the assignment id's are now integers instead of strings and when assignments are hidden in a group( as we intended to show the assignments in a group worth such and such % ) assignment id's are null. 

Technical details internally Pandas Dataframe defaults assignment id types to float when it see empty rows in columns and for some reason when it cast the id's to floats the library is changing the assignment id's that's the reason why it doesn't show all the graded assignment data

Solution: for assignment id column if a row is null the in the sql query default to 0 to escape from this bug.

**Comment by pushyamig** [comment]
Test Plan: The baseline is needed to show the same graded and ungraded assignment in the UI as in DB.

Pick a course that has a weighted assignment group with all assignments in that group are hidden in the group as we do show hidden assignment group weight in the tabular column with titled "place holder assignment" since Canvas show weighted assignment group to students.
Use the below query to validate the user submission in the DB.
```
select a.name, s.* from assignment a left join submission s on s.assignment_id=a.id where a.course_id like '%222222%' and user_id=(select user.user_id from user where sis_name = 'xxxx')
```

**Comment by jennlove-um** [comment]
Testing passed with the specified course.  Graded assignments showed up with the correct grades for the students tested.  The placeholder assignments for the weighted assignment groups also showed up correctly.
