### ISSUE TITLE
Can't change course id in Courses admin

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#613]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

## Expected behavior (A clear and concise description of what you expected to happen) : 
When I change the ID in the courses admin for a course, it should change the ID

## Describe the bug (Tell us what happens instead of the expected behavior) :
When I change the ID there is a stack trace. It looks like it creates another course with none of the default view options set with this course ID and keeps the original. The error looks like it's in Django.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in 'None'
```

## Steps to Reproduce :
1. Create a Course as admin in the Django Admin Panel
2. Change the ID number and hit Save 
3. Note that the original is not updated but a new one is created.

## Screenshots/Video (If possible, add media to help explain your problem) :
![image](https://user-images.githubusercontent.com/27447/62060343-f3ae5000-b1f2-11e9-916d-66bfd90040fc.png)

**Comment by aberatne** [comment]
I noticed that saving the course object after converting canvas id to incremented id will update the course view options after saving the course.

**Comment by aberatne** [comment]
I was trying to override the save_model() function using save(force_update=True). Is it possible to do something like this to ensure that the course instance gets the updated id instead of creating a new instance?

**Comment by jennlove-um** [comment]
Testing shows that this behavior still occurs in the most recent release.

**Comment by jennlove-um** [comment]
Testing shows that this behavior still occurs in the most recent release.

**Comment by ssciolla** [comment]
In my initial testing, I did not see the same stack trace that @jonespm highlighted in the initial issue, but I did see that a new course is created upon updating the course ID, with the old one still being there. I believe this occurs because of the `save_model` logic that also updates the primary key.

```
    # When saving the course, update the id based on canvas id
    def save_model(self, request, obj, form, change):
        obj.id = canvas_id_to_incremented_id(obj.canvas_id)
        return super(CourseAdmin, self).save_model(request, obj, form, change)
```

I guess the edited object gets saved as a brand new object because of the new primary key, and it loses the connection to the `course_view_option` data. The backend does in fact throw a 500 error if you try to access the newly created course.

We could possibly modify `save_model` to clean this up, deleting the old object and copying over the `course_view_option` data. However, there's potential for data loss here, since if the cron was run, records attached to the deleted course will also be deleted. These could just be repopulated if the cron was run again, but the `data_last_updated_at` would also have to be emptied out.

As discussed in the meeting, it seems like it a more intuitive workflow for this would be to just delete the old course and create a new one with the new ID. We can disallow changing the course ID in the admin form to prevent the bugs described in the issue.

**Comment by jennlove-um** [comment]
Testing passes in beta - the course ID is not editable.
