### ISSUE TITLE
Make  the Alerts with consistent styling

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#637]
Myla alerts users with messages in unforeseen situations, we want the alerts to be consistent in style. More details on how it needs to be styled are [here](https://github.com/tl-its-umich-edu/my-learning-analytics/wiki/MyLA-Style-Guide).

Various Alerts in App
Grade/assignments/resources - when the view is disabled
Resources - when no resource type is selected.

**Comment by justin0022** [comment]
Currently there's an `Error` component (that's under the `containers` folder - it should be moved to `components` folder). We could create some other components (like `Warning` and `Success`) that apply the correct styling.

**Comment by vjcao** [comment]
For this issue, I was considering using React Bootstrap's Alert component since the style guide emulates the alert's styles exactly. The React Bootstrap Alert component also offers a variety of variants like 'success', 'warning', 'danger' and many others (https://react-bootstrap.github.io/components/alerts). However @pushyamig found out that Material-UI and Bootstrap are both heavy and that we should just stick with Material-UI. I played around with the Bootstrap Alert component and it looks something like this:
<img width="1427" alt="Screen Shot 2019-08-07 at 10 02 07 AM" src="https://user-images.githubusercontent.com/33735083/62629514-44146480-b8fb-11e9-8216-114ea288f984.png">
Any thoughts?

**Comment by justin0022** [comment]
I agree with @pushyamig, importing React Bootstrap just for the alert components is too heavy. It should be pretty easy to build a component from scratch though. I've been using the [snackbars](https://material-ui.com/components/snackbars/) in the grade distribution view, when the user selects to enable/disable their own grade view. 

Could we use the snackbar maybe for errors?

**Comment by pushyamig** [comment]
@johnpj  what do you think of the idea of snackbar as alerts?

**Comment by jonespm** [comment]
I personally feel like "snackbar" doesn't fit the intended use of this as they are not permanent and low priority. Banner is more appropriate however I don't like the color styling of the default banners as it's not obvious that there is a warning. Maybe we could use a banner and just apply some style?

https://material.io/design/components/snackbars.html#usage

| Component | Priority | User action |
| ---- | ---- | ---- |
| Snackbar | Low priority | Optional: Snackbars disappear automatically |
| Banner | Prominent, medium priority | Optional: Banners remain until dismissed by the user, or if the state that caused the banner is resolved | 
| Dialog | Highest priority | Required: Dialogs block app usage until the user takes a dialog action or exits the dialog (if available) |

**Comment by justin0022** [comment]
Good point, a banner sounds good, styling should be straight forward.

**Comment by jonespm** [comment]
Yeah looks like there's some theming that can be applied to banners. I think that would be good.

https://material.io/design/components/banners.html#theming

Displaying a message with a little more prominent theming and  a simple action like "Dismiss" makes sense to me for these alerts.

**Comment by jennlove-um** [comment]
The banners are consistent and use the colors as discussed in #682
