### ISSUE TITLE
Check if the term on a course is set before returning a date

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#665]
#  Expected behavior (A clear and concise description of what you expected to happen) : 
If a term isn't set on a course, there is an error since the term is None and it checks self.term.date_start (and self.term.get_correct_date_end()) in these methods. It should first check that the term is available.

https://github.com/tl-its-umich-edu/my-learning-analytics/blob/d8b793e41cee29e5b808a45933918437faf26884/dashboard/models.py#L173

## Steps to Reproduce :
1. Create a course with no term, attempt to go to that course

## Workaround
Just set the term (or start/end dates) to be valid and it works, so this is lower priority, but the terms by default don't need to be set.

**Comment by jonespm** [comment]
We talked about what to return here. Either 
datetime.now()
or
datetime.MINYEAR and datetime.MAXYEAR

I feel like MINYEAR might have a larger potential for other issues so now() probably safest.

**Comment by ssciolla** [comment]
@jonespm How about something like this [commit](https://github.com/ssciolla/my-learning-analytics/commit/fd0cace1b7c8b16820a8ae5d94d26d7f64782cc9)?

Here's the modification to the `get_course_date_range` method:
```
    def get_course_date_range(self):
        if self.date_start is not None:
            start = self.date_start
        elif self.term is not None:
            start = self.term.date_start
        else:
            start = datetime.now(pytz.UTC)
        if self.date_end is not None:
            end = self.date_end
        elif self.term is not None:
            end = self.term.get_correct_date_end()
        else:
            end = start + timedelta(weeks=2)
        DateRange = namedtuple("DateRange", ["start", "end"])
        return DateRange(start, end)
```

I also updated the logic in `get_course_info` to be able to pass `None` as the value associated with the `term` key in the response object. It's debatable whether we ought to include the `term`, but I figured I'd continue to include it for now.

It's actually difficult to get the application into this state where it doesn't have an associated `AcademicTerms`, since there isn't a `blank=True` option on the field. If we merge PR #666 (which makes the `term` field read-only, it would come up when you try to visit the page before running the cron job.

**Comment by jennlove-um** [comment]
Testing passes.  I created a course with no term and did not run the chron.  I was able to go to all 3 visualization pages and to the admin screen for that course with no errors.
