### ISSUE TITLE
Allow for custom themes/styles

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#673]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added
We were thinking of easy ways that this tool could be customized for styling. If it's launched via LTI from Canvas you can use
`canvas.css.common = $Canvas.css.common
`
To get the URL to the Canvas common CSS for your theme. This is probably good, but minimally we should have a way to change the colors, fonts and some other things for each installation manually.

## Describe the solution you'd like
We could do theming but that seems like a heavy solution. Maybe [MUICSS](https://www.muicss.com/) would work? Have you considered anything for this? We'd love to at *least* have fonts and the top bar color changed for the Fall release.

**Comment by ssciolla** [comment]
I've made some progress on this issue, which you can see on my [673 issue branch](https://github.com/ssciolla/my-learning-analytics/tree/issue-673-enable-custom-themes). I just wanted to let people know to avoid duplication of effort and so @justin0022 can keep this in mind while working on PR #702. Next steps will be the following: 

1) Think about other colors used in the UI and whether they should be controlled by a theme.
2) If necessary, brainstorm ways to refactor theme use in d3 components and `RangeSlider` so that I'm not just importing `theme.js` directly. I can probably pass `theme` down through `props` or another mechanism.
