### ISSUE TITLE
Resource accessed: Add icons & revise file name display

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#693]
Resources view currently is designed to show both files/video data. 
1. Having an icon next to the resource name make it recognize what is the resource type they are looking at
2. Resource name can get long depending how instructor name it but we want to short using CSS ellipsis and on hovering over the resource name will give a complete name.

**Comment by jonespm** [comment]
The idea was to make it look a little like Canvas and have the
[Icon] [Name . . .]

With the name left aligned and truncated to fit. Not sure how many characters.

**Comment by jonespm** [comment]
Do we have a fix for this yet? I remember talking to @vjcao about the font awesome icons earlier this week.

**Comment by jennlove-um** [comment]
Feedback from today's MyLA meeting for revising this view: 

- [ ] Add the icon next to the checkboxes for the files type at the top as well to make it clear which icon is associated with each file type
- [ ]  Make the icons the same color blue as the file name link text
- [ ] Make the amount of white space consistent between the icon and the file name
- [ ] Review the fonts on the page to make sure they are all the same (different sizes are fine, but different fonts aren't)
- [ ] Left-align the text for the filters (selecting the grade range drop-down and checkboxes) and the legend (resources viewed/not viewed) to be aligned with the Y-axis.  The issue here is that there are too many different starting points for reading down the screen.

**Comment by jonespm** [comment]
I believe this should all be resolved via #766. If there's any parts missing we'll have to re-open, so will need to verify.

**Comment by jennlove-um** [comment]
There are a couple of items still open on this issue: 

Adding the icons next to the checkboxes at the top.
Aligning the filters and legend with the Y-axis.

**Comment by jennlove-um** [comment]
I've moved the incomplete items to a new issue: #869 

Testing passes for the icon next to the resource name.  The resource name truncates on the screen and hovering over it shows the entire file name.
