### ISSUE TITLE
Use the Posted date in the Submission table to determine whether to show assignment grade

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#727]
Use the posted_at attribute on the submissions_dim to determine whether the student should see an assignment grade in MyLA.

If there is a posted_at date, then the grade has been released to the student and can be displayed in MyLA's Assignment Planning page.

If there is no posted_at date, then the grade has not been released to the student and should not be in MyLA for the assignment.

**Comment by pushyamig** [comment]
Test plan:
The below query will give you released grades to a student based on `sis_name`. Go to canvas Gradebook UI and verify if this is the same. If this is not the same one reason maybe since the Data update lag between UDW and canvas Gradebook. Then you might need to do to UDW to verify the grade presence
MyLA local DB
```
select * from
(select a.name, s.* from submission s join assignment a on a.id = s.assignment_id where s.course_id like '%111111%') as sub join
(select u.sis_name,u.user_id from user u where u.course_id like '%1111%') as us on sub.user_id = us.user_id where us.sis_name='sedrftg';
```
UDW Query:
```
select sf.assignment_id,sf.score, sf.published_score, sd.posted_at from submission_fact sf join submission_dim sd on sf.submission_id = sd.id
where sf.course_id = 177000000001111111 and sf.user_id=-11111111111111111 order by sd.posted_at;
```
get the `user_id` info as below and subsitute above 
`select user_id, unique_name from pseudonym_dim where unique_name =aaaaaaa`

**Comment by jennlove-um** [comment]
@pushyamig  Can we close this one?  I think it was all tested in #728

**Comment by pushyamig** [comment]
Closing this
