### ISSUE TITLE
Make JavaScript comply with Standard linting

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#812]
Per my discussion with @ssciolla here: https://github.com/tl-its-umich-edu/my-learning-analytics/pull/775, I'm going to make every file conform to the linting rules of [Standard](https://standardjs.com/) and add a note about linting in the `CONTRIBUTING` doc.

**Comment by pushyamig** [comment]
@justin0022 You have changed all the file JS file to StandandJS, but some of the files still are not fixed in terms of formatting. 
For example, I ran again `standard --fix` this file `TableAssignment.js`, show formatting errors in IDE. 
![Screen Shot 2020-05-28 at 3 30 14 PM](https://user-images.githubusercontent.com/8579775/83184914-29b0af00-a0f8-11ea-9147-595c80bf616d.png)


This is my IDE configuration for StandardJS
![Screen Shot 2020-05-28 at 3 20 53 PM](https://user-images.githubusercontent.com/8579775/83184130-fde0f980-a0f6-11ea-98b2-48e62d6173b9.png)

I am trying to understand why even after running the `standard --fix` and configuring the IDE still shows error? is it just me or others also have the same problem.

**Comment by justin0022** [comment]
Hi @pushyamig, I've noticed this as well. 

The error when I hover over the red squiggly is: `The closing bracket must be aligned with the opening tag (expected column 17) (react/jsx-closing-bracket-location)`

I think the reason Standard doesn't auto-fix this is because it requires adding round brackets, to make the `<` and `>` align:

```js
j === 2
  ? (
    <TableCell
      title={displayProp ? prop : null} className={classes.tableCell} key={j}
      style={borderAndCurrentWeekStyle}
    >
      {displayProp ? prop : null}
    </TableCell>
  ) : (
    <TableCell className={classes.tableCell} key={j} style={borderAndCurrentWeekStyle}>
      {displayProp ? prop : null}
    </TableCell>
  )
```

Perhaps Standard isn't permitted to add any characters?

**Comment by pushyamig** [comment]
Interesting, That standard doesn't know how to fix it. Is there any doc that we can suggest for this for future reference? any suggestion

**Comment by pushyamig** [comment]
I am going to reopen this issue, as this is not resolved. I will try to have fix for this

**Comment by ssciolla** [comment]
I ran `standard` on the command line for the project and found no issues. I'm moving to Done.
