### ISSUE TITLE
[Redesign assignment] Event logging

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#877]
Send the system-generated scores when saving user defaults to Database, this is to support Event logging

**Comment by ssciolla** [comment]
@jennlove-um, is this still a requirement, or do you remember why this was needed? Personally, I think recording goals entered or locked should be enough.

**Comment by jennlove-um** [comment]
Yes, this was requested by the researchers for use in their analysis of how students use MyLA and the data they see in this screen.

**Comment by ssciolla** [comment]
Okay, as you know, the system-generated scores will change every time a goal is entered; do they want all scores ever presented to students? This is likely going to require backend work, particularly if they want to see how system-generated scores changed over time.

In terms of priorities and moving towards a release, does this seem like something to you that is needed for usability testing? I feel we could probably get this in the next release cycle prior to moving this out of `beta`.

**Comment by jennlove-um** [comment]
I don't think this needs to be there for usability testing.  It's more geared toward doing analysis of user behavior when the new assignment planning is turned on for courses.  It also sounds like it needs further definition about the research questions being asked so that we capture the right data.

**Comment by chrisrrowland** [comment]
Was there further requirement gathering for this?
Not exactly sure what the intent was here, but would this be affected if we change from target grade to minimum acceptable grade, or whatever we were talking about there?  Seems like that change would likely result in fewer target changes.

**Comment by jennlove-um** [comment]
Clarify the events that the researchers want to capture.

**Comment by jennlove-um** [comment]
For this release, capture events for the following: 
1. Course grade entered by the student.  If possible, capture what it was and what it was changed to. as well as their current grade and max possible grade at the point when they made the change.
2. Assignment grades entered by students.  If possible, capture what the grade was and what they changed it to.

**Comment by pushyamig** [comment]
Test Plan: This should log user actions individually and not as log of user action in single capture
1. When ever a user changes a course goal , it should capture current goal and previous goal changed from Like `{“courseGoalGrade”: “97”, “prevCourseGoalGrade”: “98"}`
2. When ever user changes assignment goal it should capture current and previous goal like ` {“assignmentId”: “17700000001056893”, “assignGoalGrade”: “78.8”, “assignPrevGoalGrade”: 77.8}}`

The current and Max grade value is only capture when user launch the view in a particular session with assignment and course goal. since these are not user interacted value so we just send it for first time in that session/moment they access the view

**Comment by jennlove-um** [comment]
Testing passes: Events are being logged for both setting assignment and course goals and for removing those goals.
