### ISSUE TITLE
Resource Accessed would be clearer if % on bars

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#887]
Thank you for contributing to this project!

## Describe your problem or feature you'd like added

On the resource accessed view there are numbers on the bars but no direct indication what this means. These are percentages (as indicated on the X axis and label) and would probably be better if we had a % sign after the number, like 91%.

![image](https://user-images.githubusercontent.com/27447/73946688-4f554680-48c4-11ea-825b-752e1faafcff.png)

**Comment by jennlove-um** [comment]
@vjcao & @jonespm Could we go back to rounding to whole numbers instead of to one decimal point for this one?  I don't think we need to be any more precise than the whole number. With the addition of the percent sign, having another decimal place makes the information longer than necessary with no real pay off.

**Comment by jennlove-um** [comment]
Percent displays on resource bars.  Testing passes.
