### ISSUE TITLE
[Redesign Assignment] Too many calls to GraphQL

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#892]
This is the graphQL call logs, It make like 20+ call for setting the user defaults and event logs got messed up too

![Screen Shot 2020-02-03 at 8 01 26 AM](https://user-images.githubusercontent.com/8579775/73655242-84129500-465b-11ea-97e1-4cd07e505796.png)

**Comment by justin0022** [comment]
I'm not able to recreate the too many calls, but not sure about the event logs.

**Comment by pushyamig** [comment]
I was the person who reported this when Reviewing the assignment redesign and @justin0022 made a fix (probably relating to something else) that fixed this infinity look-a-like graphQL call. This should be fixed

**Comment by pushyamig** [comment]
@ssciolla You can review this for Dev/QA testing

**Comment by ssciolla** [comment]
Yeah, I'm not seeing the repeated GraphQL calls anymore. There is only one call for a change to a goals and one for clearing of goals. 

I am seeing calls for every character change in goal inputs, which seems excessive; I think we should probably set a delay so that it waits a second or two for other changes before storing what's there. I thought I remember it waiting for you to click away, but that doesn't seem to be the case anymore.  This is a separate issue I think. I'll look for something related to this and create one if I don't find it.

Meanwhile, I'm moving this issue to Done.
