### ISSUE TITLE
LTI integration & SameSite readiness

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#962]
Instructors need to be able to add MyLA to courses as an LTI

This is the highest priority for Fall 2020.

**Comment by jennlove-um** [comment]
- [ ] Instructor admin page to configure MyLA for their course (#849 )
- [ ] Manage course end dates (#963 )

**Comment by jennlove-um** [comment]
Notes from discussion: 
Can we upgrade to New LTI version for Myla instead of 1.1? (We can but it might either require writing a new Django Middleware or finding one, I haven't seen one yet)

1.3 library: new library available other than django-tsugi. PyLTI1.3 as of March 2020.
https://github.com/dmitry-viskov/pylti1.3-django-example

**Comment by pushyamig** [comment]
How are we planning to add Myla as LTI tool? are we adding it by default in the side navigation or make it available in the Canvas App at the account level so that instructor can add it to their course if they prefer.

**Comment by pushyamig** [comment]
Since we are planning on a on demand cron approach i.e if an instructor enables it from the App list and (Hopefully) launches the tools then we create a his course entry in the course table. Later when the cron run we can load the data he needs.

I see that as part of the launch we get passed in different roles the user has in Canvas, not just single role.

For example,
['http://purl.imsglobal.org/vocab/lis/v2/institution/person#Student'
'http://purl.imsglobal.org/vocab/lis/v2/institution/person#Instructor'
'http://purl.imsglobal.org/vocab/lis/v2/institution/person#Student'
'http://purl.imsglobal.org/vocab/lis/v2/system/person#User'
'http://purl.imsglobal.org/vocab/lis/v2/membership#Learner'
'http://purl.imsglobal.org/vocab/lis/v2/system/person#User']

membership is the one that actually give info about his role in the course.
I see that for 
`instructor: http://purl.imsglobal.org/vocab/lis/v2/membership#Instructor`
`Assistance: http://purl.imsglobal.org/vocab/lis/v2/membership#Instructor`
`TA: [http://purl.imsglobal.org/vocab/lis/v2/membership#Instructor,http://purl.imsglobal.org/vocab/lis/v2/membership/Instructor#TeachingAssistant]`

Some time a TA is instructor in certain section and just a TA in certain sections, I am assuming TA will never be a instructor in the actual course but can be instructor in a section and TA in another course section

With Assistant he is always sent as Instructor unless you enable this variable `$Canvas.membership_roles` in the LTI custom parameters it will righteously send his role as Assistant, But With TA this custom param send enrollment as TA and Instructor.

Which user ( Instructor, TA, Assistant) launch action should we enable cron process or in other words adding an entry in course table? 

If we add it as a default to side navigation then their is rick that instructor will never launches the tool and Myla in a way disabled for that course/s

**Comment by jonespm** [comment]
1) The plan was to add it as an LTI tool at the account level so the instructors would have to enable it. We aren't turning it on by default for all courses. This is why without a tool like "Faculty Tools" I don't think we'll get much adoption as discovering and enabling tools isn't very easy.

2) I think it's going to have to be the instructor that does a launch. As you said TA's are often for sections only and we don't have section support (this feature was determined to be low priority). So in order for the course to get added

1) Instructor adds the LTI tool manually from the Settings tool.
2) Instructor clicks on the tool in the left nav
  This launches the LTI tool and adds it to an available course if they are an instructor
3) Instructor enables the views they want for the course (in whatever UI is designed for that)
4) Instructor (and students) wait for the next cron run.

**Comment by pushyamig** [comment]
I also see that Assistant are also given instructor role from default launch parameter. There is no LTI role mapped. I need to add Custom launch parameter `$Canvas.membership_roles` to differentiate between Assistant and instructor.

**Comment by jennlove-um** [comment]
I think that it would be okay to allow Assistants to add MyLA to a Canvas course.  Based on the documentation of Canvas roles at UM, Assistants have all the same permissions as Teachers, just a different role name.

**Comment by jennlove-um** [comment]
Testing passes for teacher and assistant roles.  Both can add MyLA to a course and get the correct message about data being processed.  Both have access to enable and disable views.
