### ISSUE TITLE
Change the Resources ETL to use a daily-delta approach

### ISSUE THREAD

**Issue by jennlove-um** [tl-its-umich-edu/my-learning-analytics#973]
Update the ETL to use a delta approach instead of dropping all data and reloading.

**Comment by jonespm** [comment]
We are going to tackle this first for resources/bigquery. Sam also commented that having a FK between resources -> resource_accessed would help keep things clean when files are no longer available.

**Comment by jonespm** [comment]
So this upsert (resources) seems to be running into some issues with our data model making this hard to fix. Back in #918 we added an id because Django doesn’t seem to support more than one primary key and this needed a key on resource_id and course_id. What a pain. 

We need to actually be able to upsert in the `resource` table. The resource_access we can just append new records and I guess not worry about it. 

What we probably really need is either foreign keys or a new table like
`resource_course`

That links together resource and course. But we still can't have a table like this in Django and make it updatable. I can think of how to fix this in SQLAlchemy but not in any way Django will really like yet.

If I put the multiindex back I think I can get this to work with the cron/pandas, but not sure about Django.

`ALTER TABLE resource DROP id, ADD PRIMARY KEY(resource_id,course_id);`

Thinking about what to do here.

**Comment by jonespm** [comment]
Perhaps we could switch to just managing this entirely in Django? Would that even be possible? @ssciolla did your code do something like this?

I feel like we'd need more foreign keys.

```
on Resource
course_id = models.ForeignKey(Courses)

on ResourceAccess
resource_id = models.ForeignKey(Resource)
user_id = models.ForeignKey(User)

```
Then we'd need some code class that could take the dataframe and upsert against these Django models, maybe with [bulk_update](https://docs.djangoproject.com/en/3.0/ref/models/querysets/#bulk-update)? I'm not 100% sure what would give the best performance.

Maybe just not care about performance of the resource table since it won't have a ton of records anyway. . . Just thinking still about this.

**Comment by ssciolla** [comment]
Yeah, if we're fiddling around with these tables/models, we should probably fix the relationship between `resource` and `course` with some kind of M:M table. It seems a little silly because Canvas resources can't be shared between course (I think), but we may have to bite the bullet and just do it.

I'll have to think about the best way of updating `resource` and `resource_course` (gotta be better name, haven't figured it out yet) using Django. I'll DM you.

**Comment by ssciolla** [comment]
Assuming you have these tables/models wired together as you've described with FKs and M:M relationship between to `course` and `resource`, could you do something like this?

* Upsert and delete records using whatever method you'd like -- `pandas`, `pangres`, or Django ORM -- in the `resource` table. Deleting `resource` records means records in `resource_course` and `resource_access` are also deleted via `CASCADE`.
* Insert new records M:M records to `resource_course` via `pandas` or Django `bulk_create`.
* Insert new records to `resource_access`.

This change in the data model may require some re-tooling of the associated Resources Accessed view, but ultimately it may simplify the code, particularly if you take full advantage of the [`ManyToManyField` stuff](https://docs.djangoproject.com/en/3.0/ref/models/fields/#manytomanyfield).

**Comment by jonespm** [comment]
Yeah it sounds like this would work but would be a refactor and possibly a view change.

I don't know how Django can manage the resource_course table though and was going to experiment.

For resource_course table in the database it seems like it would have to be a dual primary key link table of

```
resource_id PK
course_id PK
```

Or to make Django happy
```
id PK
resource_id (unique_together)
course_id (unique_together)
```

Or just drop this link table entirely.

I was thinking about creating the models.py the way I'd want it to work and seeing what migrations Django creates and using that. And trying to then force the data into it. Probably early next week. I think we should work toward improving this model though. 

It started out 100% as to_sql created which is why it's not great with little thought into ideal relationships. Django models were created to match this existing model. That seems like the wrong way to go about this.

**Comment by jonespm** [comment]
So I thought of a problem with this and think I'll open a new issue about it.

If a course is added part way through the semester (or even a week later) it's events will only populate from the time it's added.

To fix this I believe we'll have to make the job 
* Check if there are any courses newly added since the last run
* If there are, run the update from the start of the term for the new courses

I believe checking if there are new courses might be useful for other reasons (like if we wanted the cron to run more frequently). For instance we *could* run the cron hourly but only if there's new courses, otherwise we'd just do the daily run.

**Comment by zqian** [comment]
Wow, since the first time this applied to cron job, the cost of selects from BigQuery was reduced from 

TBytes billed for BQ: 2.088888168334961 = $10.44

to

TBytes billed for BQ: 0.013109207153320312 = $0.07

Big savings indeed!
