### ISSUE TITLE
API entry to support course config

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/my-learning-analytics#985]
Implement an API entry to support the UI changes described in #849.

Requirements:

* [x] Accept Boolean values for each of the available visualizations (currently 4) to indicate whether they are visible to students.
* [x] Accept Boolean value for whether the `show_grade_counts` feature is enabled.
* [ ] Allow requests only from instructor-like users.
* [x] If possible, accept partial requests.  That is, allow values for as few as one configuration option, as many as all of them, and any number in between.  That will enable the UI to save the values individually, as the user specifies them.

**Comment by lsloan** [comment]
@chrisrrowland, tell me what you think of this.  If this doesn't sound like it will meet the needs the the UI you're implementing, tell me what you'll need.

**Comment by chrisrrowland** [comment]
This sounds pretty good to me.  

From my perspective it would be idea if all 5 options were handled the same way and the api can abstract away the implementation being in different tables.
I'm not 100% sure about the possible issues that would exist with this, as it sounds like these were put into different tables with a specific intent.

Additionally it might be nice if there was a new API for getting all of these settings and a data model that we could use consistently for the get/set operations.  This is a nice to have since we can get that info already in other ways, but it might be a nice implementation.  We can talk about what might work best for this.

I think the partial request idea is also good.. I imagine it could accept an array of setting values and just operate on that.  Success/failure would still be determined on an individual level.

**Comment by lsloan** [comment]
Although [it was discussed](849#issuecomment-655540582) somewhat in #849, I also don't understand why `show_grade_counts` is an attribute of `Course` rather than of the visualization(s).

I think new models and APIs for the visualizations is needed, too.  However, I think it's outside the scope of this issue.  I would expect to see classes for `Visualization` and `VisualizationOptions` that define what visualizations are available and what are their options.  There would be corresponding `CourseVisualization` and `CourseVisualizationOptions` that contain the visualization values for each course.

**Comment by lsloan** [comment]
I plan to write a new API entry that **_requires_** the HTTP `PUT` method.  We can discuss whether using `POST` or `PATCH` would be more appropriate.

It would accept a body containing the JSON:

```JSON
{
  "course_view_options": {
    "ra": true,
    "apv1": true,
    "ap": true,
    "gd": true
  },
  "show_grade_counts": false
}
```

* Both top-level keys are optional
* In the `course_view_options` object, all keys are optional
* The body **_must_** contain at least one **_Boolean_** value for one of the **_allowed_** keys
* Requests with unrecognized keys or body structure will be **_disallowed_**  
  (Key order is unimportant.)
* Requests with the wrong method will be **_disallowed_**

**Comment by chrisrrowland** [comment]
So the thoughts I had [posted ](https://github.com/tl-its-umich-edu/my-learning-analytics/issues/849#issuecomment-655714076)in #849 allowed the UI to be driven completely by the data model and would allow the UI to automatically update as new options were added.  It incorporates the hierarchy of settings that are dependent on other settings.  Really there is only the one, show_grade_counts, which is dependent on gd (I think?)  I didn't include the code ("ra", "apv1", etc) in the model but it might make sense to include that as well.

That could be entirely over engineered and/or not as future proof as I thought it might be, though.

Your proposal would work as well, but it does put the onus on the UI to know how options are related to one another, if it is desirable in the first place to display them in such a way (hierarchical check boxes or what not)

I do think fundamentally the api is the place you'd generally want to hide any backend nuance (which is what im calling the options being in different places)

Not sure what your thoughts are on that

Not sure what your thoughts are about that.

**Comment by lsloan** [comment]
> I do think fundamentally the api is the place you'd generally want to hide any backend nuance (which is what im calling the options being in different places)

Is the suggestion that I not use the "course_view_options" object in the JSON?  I put it there because I thought it was helpful to group the "is this visualization enabled" options separate from others.  If you think that's not necessary, I could remove it.  The API entry would instead accept:

```JSON
{
  "ra": true,
  "apv1": true,
  "ap": true,
  "gd": true,
  "show_grade_counts": false
}
```

That would make the input validation code simpler, too.

If that's not what you had in mind, please leave a comment here with an example of the JSON you'd like the API entry to accept.

**Comment by chrisrrowland** [comment]
The model i put together just so I could start mucking around with the front end was like this
```
[  
    { 'id':'apv1', 'name':'Assignment Planning V1',  'enabled':false, 'options' : [] },
    { 'id':'ap',   'name': 'Assignment Planning V2', 'enabled':true, 'options' : [] },
    { 'id':'gd',   'name': 'Grade Distribution',     'enabled':true, 'options' : [ {'id':'show_grade_counts', 'name':'Show Grade Counts', 'enabled':true, 'options':[]}]},
    { 'id':'ra',   'name': 'Resources Accessed',     'enabled':true, 'options' : [] },
]
```
![image](https://user-images.githubusercontent.com/17617998/87794116-2abaae80-c814-11ea-9f0a-16492ba7bb8b.png)


This represented the data model I needed for the UI, though, and there is no reason to pass the name back to the API when updating an option so that part of the model wouldn't be necessary in that exchange.

I had done this b/c it contained the hierarchical representation of the options (show_grade_counts is really an option of the Grade Distribution, etc) however I am not entirely sure it is worth adding that level of complexity now, or if its more of a case of optimizing for future enhancements that might not end up looking anything like these options and not even fit the model.

The upside is that i was thinking I could call a GetOptions api to retrieve such a data model, and SetOptions to push updates using the same (or minimal viable part of the model) to update.
It allows the UI to be dynamically generated based on the options in the model. (with my newness to react I'm currently struggling to get the state binding working when generating the UI this way, though, but im sure it can be done)

Downside is that the recursive model definitely complicates things. Either you have to enforce all of the id's are unique, which the database model cannot currently do since they live in different tables, or you have to pass top level options to the api if you want to update a nested option.  It's also unclear if we ultimately want the UI to present the options hierarchically, so perhaps all of that is pointless.

I do think either the flat option you proposed above, or the recursive option i mentioned would be better than the original segmented model, because I'm not sure that there is any value having those options treated differently unless treating them differently provides you with additional information which really doesn't exist in the model where show_grade_counts is singled out.

**Comment by chrisrrowland** [comment]
Re: having to pass top level options, i had actually been thinking I could set nested options directly by passing concatenated ids, but that might be messy.


{'name':'gd.Show Grade Counts', 'enabled':true, 'options':[] }

**Comment by lsloan** [comment]
> `{'name':'gd.Show Grade Counts', 'enabled':true, 'options':[] }`

I think that would be trickier for the API to validate.

I'm starting to lean towards using the "jsonschema" Python module to validate the input using the JSON Schema standard.  I hope the form of input we want to use won't make it too difficult to define a (brief) schema for it.  I mean, any JSON input can have a schema defined for it, but it could become long and unruly, making our code more difficult to maintain, etc.

That said, I won't let using a module like jsonschema become an artificial barrier to our progress.  I can drop it and write single purpose validation code instead, if necessary.

Taking inspiration from your suggestions, what do you think of JSON like:

```json
{
  "apv1": { "enabled": false },
  "ap": { "enabled": true },
  "gd": { "enabled": true, "show_grade_counts": true },
  "ra": { "enabled": true }
}
```

Where each of the top level keys is optional and `show_grade_counts` is, too.  If a top level key is given, its object must have a `enabled` key within it.  If `gd` were specified without `show_grade_counts`, then that option would be unchanged.

**Comment by chrisrrowland** [comment]
I think based on the discussion we just had that will work well.

**Comment by pushyamig** [comment]
As views are being toggled, Api calls updates the course view table and right views are enabled to used based on the user criteria

Test passes
